# Site settings
title: Gaurav Keswani’s Blog
email: gauravkeswani92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   This blog will primarily have programming topics. I generally make notes
   while I am studying and thought that this would be a good way
   of keeping everything organised. Feel free to explore and suggest any
   code improvements!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Gaurav_Keswani
github_username:  gkeswani92
linked_username: gauravkeswani
facebook_name: gaurav_keswani

# Build settings
markdown: kramdown
